<!DOCTYPE html>
<html lang="en"><head>
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Jeff Jacobs">
  <title>DSAN 5300-02 – Week 2: Linear Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-e25fdd79262ba544bd7e51cad97db23a.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/simplemenu/simplemenu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 2: Linear Regression</h1>
  <p class="subtitle"><em>DSAN 5300: Statistical Learning</em><br><span class="subsubtitle">Spring 2026, Georgetown University</span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jeff Jacobs 
</div>
        <p class="quarto-title-affiliation">
            <a href="mailto:jj1088@georgetown.edu"><code>jj1088@georgetown.edu</code></a>
          </p>
    </div>
</div>

  <p class="date">Monday, January 12, 2026</p>
</section>
<section id="schedule" class="title-slide slide level1 smaller small-title crunch-title crunch-callout center" data-name="Schedule">
<h1>Schedule</h1>
<p>Today’s Planned Schedule:</p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Start</th>
<th style="text-align: left;">End</th>
<th style="text-align: left;">Topic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Lecture</strong></td>
<td style="text-align: left;">6:30pm</td>
<td style="text-align: left;">7:10pm</td>
<td style="text-align: left;"><a href="#/linear-regression">Simple Linear Regression →</a></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">7:10pm</td>
<td style="text-align: left;">7:30pm</td>
<td style="text-align: left;"><a href="#/deriving-the-least-squares-estimate">Deriving the OLS Solution →</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">7:30pm</td>
<td style="text-align: left;">8:00pm</td>
<td style="text-align: left;"><a href="#/interpreting-output">Interpreting OLS Output →</a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Break!</strong></td>
<td style="text-align: left;">8:00pm</td>
<td style="text-align: left;">8:10pm</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">8:10pm</td>
<td style="text-align: left;">8:30pm</td>
<td style="text-align: left;"><a href="#/quiz-review">Quiz Review →</a></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">8:30pm</td>
<td style="text-align: left;">9:00pm</td>
<td style="text-align: left;">Quiz 2!</td>
</tr>
</tbody>
</table>
</section>

<section>
<section id="linear-regression" class="title-slide slide level1 title-12 crunch-title crunch-ul crunch-li-8 center" data-stack-name="Linear Regression">
<h1>Linear Regression</h1>
<ul>
<li><p>What happens to my <strong>dependent variable</strong> <span class="math inline">\(Y\)</span> when my <strong>independent variable</strong> <span class="math inline">\(X\)</span> increases by <strong>1 unit</strong>?</p></li>
<li><p>Keep the <strong>goal</strong> in front of your mind:</p>
<div class="r-fit-text" title="<i class='bi bi-bullseye'></i> The Goal of Regression">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong><i class="bi bi-bullseye"></i> The Goal of Regression</strong></p>
</div>
<div class="callout-content">
<p><strong>Find a line <span class="math inline">\(\widehat{y} = mx + b\)</span> that best predicts <span class="math inline">\(Y\)</span> for given values of <span class="math inline">\(X\)</span></strong></p>
</div>
</div>
</div>
</div></li>
</ul>
<div id="sanity-notes" style="font-size: 67%">
<ul>
<li><em>Sanity Note 1</em>: <i class="bi bi-bullseye"></i> <span class="math inline">\(\Rightarrow\)</span> measuring error via <strong>vertical</strong> distance from line</li>
<li><em>Sanity Note 2:</em> <i class="bi bi-bullseye"></i> <span class="math inline">\(\Rightarrow\)</span> modeling distribution of <span class="math inline">\(\boxed{Y \mid X}\)</span>, not <span class="math inline">\((X,Y)\)</span>!
<ul>
<li>Predicting <span class="math inline">\(Y\)</span> from <span class="math inline">\(X\)</span> <strong><em>and</em></strong> <span class="math inline">\(X\)</span> from <span class="math inline">\(Y\)</span> <span class="math inline">\(\Rightarrow\)</span> <strong>principal component line <span class="math inline">\(\neq\)</span> regression</strong>!</li>
</ul></li>
</ul>
</div>
<div class="hidden">

</div>
<div class="hidden">
<p><span class="math display">\[
\DeclareMathOperator*{\argmax}{argmax}
\DeclareMathOperator*{\argmin}{argmin}
\newcommand{\bigexp}[1]{\exp\mkern-4mu\left[ #1 \right]}
\newcommand{\bigexpect}[1]{\mathbb{E}\mkern-4mu \left[ #1 \right]}
\newcommand{\definedas}{\overset{\small\text{def}}{=}}
\newcommand{\definedalign}{\overset{\phantom{\text{defn}}}{=}}
\newcommand{\eqeventual}{\overset{\text{eventually}}{=}}
\newcommand{\Err}{\text{Err}}
\newcommand{\expect}[1]{\mathbb{E}[#1]}
\newcommand{\expectsq}[1]{\mathbb{E}^2[#1]}
\newcommand{\fw}[1]{\texttt{#1}}
\newcommand{\given}{\mid}
\newcommand{\green}[1]{\color{green}{#1}}
\newcommand{\heads}{\outcome{heads}}
\newcommand{\iid}{\overset{\text{\small{iid}}}{\sim}}
\newcommand{\lik}{\mathcal{L}}
\newcommand{\loglik}{\ell}
\DeclareMathOperator*{\maximize}{maximize}
\DeclareMathOperator*{\minimize}{minimize}
\newcommand{\mle}{\textsf{ML}}
\newcommand{\nimplies}{\;\not\!\!\!\!\implies}
\newcommand{\orange}[1]{\color{orange}{#1}}
\newcommand{\outcome}[1]{\textsf{#1}}
\newcommand{\param}[1]{{\color{purple} #1}}
\newcommand{\pgsamplespace}{\{\green{1},\green{2},\green{3},\purp{4},\purp{5},\purp{6}\}}
\newcommand{\pedge}[2]{\require{enclose}\enclose{circle}{~{#1}~} \rightarrow \; \enclose{circle}{\kern.01em {#2}~\kern.01em}}
\newcommand{\pnode}[1]{\require{enclose}\enclose{circle}{\kern.1em {#1} \kern.1em}}
\newcommand{\ponode}[1]{\require{enclose}\enclose{box}[background=lightgray]{{#1}}}
\newcommand{\pnodesp}[1]{\require{enclose}\enclose{circle}{~{#1}~}}
\newcommand{\purp}[1]{\color{purple}{#1}}
\newcommand{\sign}{\text{Sign}}
\newcommand{\spacecap}{\; \cap \;}
\newcommand{\spacewedge}{\; \wedge \;}
\newcommand{\tails}{\outcome{tails}}
\newcommand{\Var}[1]{\text{Var}[#1]}
\newcommand{\bigVar}[1]{\text{Var}\mkern-4mu \left[ #1 \right]}
\]</span></p>
</div>
</section>
<section id="how-do-we-define-best" class="slide level2 smaller crunch-title crunch-ul crunch-quarto-figure crunch-img crunch-li-8">
<h2>How Do We Define “Best”?</h2>
<ul>
<li>Intuitively, two different ways to measure <strong>how well a line fits the data</strong>:</li>
</ul>
<div class="quarto-layout-panel" data-layout="[1,1]">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div id="fig-pc-line" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-pc-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="index_files/figure-revealjs/fig-pc-line-1.png" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pc-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The line that minimizes blue distances does <strong>not</strong> predict <span class="math inline">\(Y\)</span> as well as regression line, despite intuitive appeal!
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell-output-display">
<div id="fig-reg-line" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-reg-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="index_files/figure-revealjs/fig-reg-line-1.png" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reg-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The line that minimizes green distances <strong>optimally</strong> predicts <span class="math inline">\(Y\)</span> from <span class="math inline">\(X\)</span>, in a mathematically-provable sense!
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>

<aside><div>
<p>On the difference between these two lines, and why it matters, I cannot recommend <span class="citation" data-cites="gelman_data_2007">Gelman and Hill (<a href="#/references" role="doc-biblioref" onclick="">2007</a>)</span> enough!</p>
</div></aside></section>
<section id="principal-component-analysis" class="slide level2 smaller crunch-title crunch-ul shift-footnotes-20 crunch-li-8">
<h2>Principal Component Analysis</h2>
<ul>
<li><strong>Principal Component Line</strong> can be used to <strong>project</strong> the data onto its <strong>dimension of highest variance</strong> (recap from 5000!)</li>
<li>More simply: PCA can <strong>discover</strong> meaningful axes in data (<strong>unsupervised</strong> learning / <strong>exploratory</strong> data analysis settings)</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/gdp-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>

<aside><div>
<p>See <a href="https://juliasilge.com/blog/un-voting/">this amazing blog post</a> using PCA, with 2 dimensions, to explore UN voting patterns!</p>
</div></aside></section>
<section id="create-your-own-dimension" class="slide level2">
<h2>Create Your Own Dimension!</h2>

<img data-src="index_files/figure-revealjs/pca-plot-1.png" width="960" class="r-stretch"></section>
<section id="and-use-it-for-eda" class="slide level2">
<h2>…And Use It for EDA</h2>

<img data-src="index_files/figure-revealjs/pca-facet-plot-1.png" width="960" class="r-stretch"></section>
<section id="but-in-our-case" class="slide level2 crunch-title crunch-ul text-90">
<h2>But in Our Case…</h2>
<ul>
<li><span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> dimensions <strong>already have meaning</strong>, and we have a <strong>hypothesis</strong> about effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span>!</li>
</ul>
<div title="The Regression Hypothesis $\mathcal{H}_{\text{reg}}$">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Regression Hypothesis <span class="math inline">\(\mathcal{H}_{\text{reg}}\)</span></strong></p>
</div>
<div class="callout-content">
<p>Given data <span class="math inline">\((X, Y)\)</span>, we estimate <span class="math inline">\(\widehat{y} = \widehat{\beta}_0 + \widehat{\beta}_1x\)</span>, hypothesizing that:</p>
<ul>
<li>Starting from <span class="math inline">\(y = \underbrace{\widehat{\beta}_0}_{\mathclap{\text{Intercept}}}\)</span> when <span class="math inline">\(x = 0\)</span>,</li>
<li>An <strong>increase</strong> of <span class="math inline">\(x\)</span> by <strong>1 unit</strong> is associated with an <strong>increase</strong> of <span class="math inline">\(y\)</span> by <strong><span class="math inline">\(\underbrace{\widehat{\beta}_1}_{\mathclap{\text{Coefficient}}}\)</span> units</strong></li>
</ul>
</div>
</div>
</div>
</div>
<ul>
<li>We want to measure <strong>how well</strong> our line predicts <span class="math inline">\(y\)</span> for any given <span class="math inline">\(x\)</span> value <span class="math inline">\(\implies\)</span> <strong>vertical distance</strong> from regression line</li>
</ul>
</section>
<section id="example-advertising-effects" class="slide level2 smaller title-12 crunch-title crunch-ul">
<h2>Example: Advertising Effects</h2>
<ul>
<li><strong>Independent variable</strong>: $ put into advertisements; <strong>Dependent variable</strong>: Sales</li>
<li><strong>Goal 1</strong>: <em>Predict</em> sales for a given allocation</li>
<li><strong>Goal 2</strong>: <em>Infer</em> best allocation for a given advertising budget (more simply: a new $1K appears! Where should we invest it?)</li>
</ul>

<img data-src="index_files/figure-revealjs/ad-plots-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="simple-linear-regression" class="slide level2 smaller crunch-title crunch-ul crunch-math">
<h2>Simple Linear Regression</h2>
<ul>
<li>For now, we treat <strong>Newspaper</strong>, <strong>Radio</strong>, <strong>TV</strong> advertising separately: how much do <strong>sales</strong> increase per $1 into [medium]? (Later we’ll consider them jointly: multiple regression)</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<center>
<p><strong>Our model</strong>:</p>
</center>
<p><span class="math display">\[
Y = \underbrace{\param{\beta_0}}_{\mathclap{\text{Intercept}}} + \underbrace{\param{\beta_1}}_{\mathclap{\text{Slope}}}X + \varepsilon
\]</span></p>
</div><div class="column" style="width:50%;">
<center>
<p>…Generates <strong>predictions</strong> via:</p>
</center>
<p><span class="math display">\[
\widehat{y} = \underbrace{\widehat{\beta}_0}_{\mathclap{\small\begin{array}{c}\text{Estimated} \\[-5mm] \text{intercept}\end{array}}} ~+~ \underbrace{\widehat{\beta}_1}_{\mathclap{\small\begin{array}{c}\text{Estimated} \\[-4mm] \text{slope}\end{array}}}\cdot x
\]</span></p>
</div></div>
<ul>
<li>Note how these predictions will be <strong>wrong</strong> (unless the data is perfectly linear)</li>
<li>We’ve accounted for this in our model (by including <span class="math inline">\(\varepsilon\)</span> term)!</li>
<li>But, we’d like to find estimates <span class="math inline">\(\widehat{\beta}_0\)</span> and <span class="math inline">\(\widehat{\beta}_1\)</span> that produce the <strong>“least wrong” predictions</strong>: motivates focus on <strong>residuals <span class="math inline">\(\widehat{\varepsilon}_i\)</span>…</strong></li>
</ul>
<p><span class="math display">\[
\widehat{\varepsilon}_i = \underbrace{y_i}_{\mathclap{\small\begin{array}{c}\text{Real} \\[-5mm] \text{label}\end{array}}} - \underbrace{\widehat{y}_i}_{\mathclap{\small\begin{array}{c}\text{Predicted} \\[-5mm] \text{label}\end{array}}}
= \underbrace{y_i}_{\mathclap{\small\begin{array}{c}\text{Real} \\[-5mm] \text{label}\end{array}}} - \underbrace{
  \left(
    \widehat{\beta}_0 + \widehat{\beta}_1 \cdot x
  \right)
}_{\text{\small{Predicted label}}}
\]</span></p>
</section>
<section id="least-squares-minimizing-residuals" class="slide level2 smaller crunch-title title-11 crunch-quarto-figure crunch-p crunch-quarto-layout-panel crunch-img">
<h2>Least Squares: Minimizing Residuals</h2>
<p>What can we <strong>optimize</strong> to ensure these residuals are as small as possible?</p>
<div class="quarto-layout-panel" data-layout="[65,35]">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="column quarto-layout-cell" style="flex-basis: 65.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/large-resids-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column quarto-layout-cell" style="flex-basis: 35.0%;justify-content: flex-start;">
<p>Sum?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>0.0000000000</code></pre>
</div>
</div>
<p>Sum of Squares?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>3.8405017200</code></pre>
</div>
</div>
<p>Sum of absolute vals?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>7.6806094387</code></pre>
</div>
</div>
</div></div>
</div>
<div class="quarto-layout-panel" data-layout="[65,35]">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="column quarto-layout-cell" style="flex-basis: 65.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/small-resids-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column quarto-layout-cell" style="flex-basis: 35.0%;justify-content: flex-start;">
<p>Sum?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>0.0000000000</code></pre>
</div>
</div>
<p>Sum of Squares?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>1.9748635217</code></pre>
</div>
</div>
<p>Sum of absolute vals?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>5.5149697440</code></pre>
</div>
</div>
</div></div>
</div>
</section>
<section id="why-not-absolute-value" class="slide level2 smaller crunch-title crunch-code crunch-ul crunch-quarto-figure">
<h2>Why Not Absolute Value?</h2>
<ul>
<li>Two feasible ways to prevent positive and negative residuals <strong>cancelling out</strong>:
<ul>
<li><span class="cb1"><strong>Absolute error</strong> <span class="math inline">\(\left|y - \widehat{y}\right|\)</span></span> or <span class="cb2"><strong>squared error</strong> <span class="math inline">\(\left( y - \widehat{y} \right)^2\)</span></span></li>
</ul></li>
<li>But remember: we’re aiming to <strong>minimize</strong> 👀 these residuals; ghost of calculus past 😱</li>
<li>We <em>minimize</em> by taking <em>derivatives</em>… which one is <strong>differentiable</strong> everywhere?</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/abs-x-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/x2-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="outliers-penalized-quadratically" class="slide level2 smaller crunch-title crunch-ul crunch-quarto-layout-panel">
<h2>Outliers Penalized Quadratically</h2>
<ul>
<li>May feel arbitrary at first (we’re “forced” to use squared error because of calculus?)</li>
<li>It also has <strong>important consequences</strong> for “learnability” via gradient descent!</li>
</ul>
<div class="quarto-layout-panel" data-layout="[1,1]">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="column quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/resid-quadratic-abs-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/resid-quadratic-squared-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="key-features-of-regression-line" class="slide level2 crunch-math math-90">
<h2>Key Features of Regression Line</h2>
<ul>
<li>Regression line is <strong>BLUE</strong>: <strong>B</strong>est <strong>L</strong>inear <strong>U</strong>nbiased <strong>E</strong>stimator</li>
<li>What exactly is it the “best” linear estimator of?</li>
</ul>
<p><span class="math display">\[
\widehat{y} = \underbrace{\widehat{\beta}_0}_{\mathclap{\small\begin{array}{c}\text{Estimated} \\[-5mm] \text{intercept}\end{array}}} ~+~ \underbrace{\widehat{\beta}_1}_{\mathclap{\small\begin{array}{c}\text{Estimated} \\[-4mm] \text{slope}\end{array}}}\cdot x
\]</span></p>
<p>is chosen so that</p>
<div class="smallmath">
<p><span class="math display">\[
\widehat{\theta} = \left(\widehat{\beta}_0, \widehat{\beta}_1\right) = \argmin_{\beta_0, \beta_1}\left[ \sum_{x_i \in X} \left(~~\overbrace{\widehat{y}(x_i)}^{\mathclap{\small\text{Predicted }y}} - \overbrace{\expect{Y \mid X = x_i}}^{\small \text{Avg. }y\text{ when }x = x_i}\right)^{2~} \right]
\]</span></p>
</div>
</section>
<section id="where-did-that-mathbbey-mid-x-x_i-come-from" class="slide level2 smaller title-11">
<h2>Where Did That <span class="math inline">\(\mathbb{E}[Y \mid X = x_i]\)</span> Come From?</h2>
<ul>
<li>From our assumption that the irreducible <strong>errors</strong> <span class="math inline">\(\varepsilon_i\)</span> are <strong>normally distributed</strong> <span class="math inline">\(\mathcal{N}(0, \sigma^2)\)</span></li>
</ul>

<img data-src="images/regression_normal_dist.jpg" class="r-stretch quarto-figure-center"><p class="caption"><a href="https://digfir-published.macmillanusa.com/psbe4e/psbe4e_ch10_2.html">Image Source</a></p><ul>
<li>Kind of an immensely important point, since it <strong>gives us a hint for checking whether model assumptions hold</strong>: spread around the regression line should be <span class="math inline">\(\mathcal{N}(0, \sigma^2)\)</span></li>
</ul>
</section>
<section id="heteroskedasticity" class="slide level2 smaller crunch-title">
<h2>Heteroskedasticity</h2>
<ul>
<li>If spread <strong>increases</strong> or <strong>decreases</strong> for larger <span class="math inline">\(x\)</span>, for example, then <span class="math inline">\(\varepsilon \nsim \mathcal{N}(0, \sigma^2)\)</span></li>
</ul>

<img data-src="images/3_11.svg" class="r-stretch quarto-figure-center"><p class="caption">Figure 3.11 from <span class="citation" data-cites="james_introduction_2023">James et al. (<a href="#/references" role="doc-biblioref" onclick="">2023</a>)</span></p></section>
<section id="but-what-about-other-types-of-vars" class="slide level2 title-08 crunch-title text-90">
<h2>But… What About Other Types of Vars?</h2>
<ul>
<li>5000: you saw <strong>nominal</strong>, <strong>ordinal</strong>, <strong>cardinal</strong> vars</li>
<li>5100: you wrestled with <strong>discrete</strong> vs.&nbsp;<strong>continuous</strong> RVs</li>
<li>Good News #1: Regression can handle <strong>all</strong> these types+more!</li>
<li>Good News #2: Distinctions between <strong>classification</strong> and <strong>regression</strong> diminish as you learn fancier regression methods!
<ul>
<li>tldr: Predict continuous probabilities <span class="math inline">\(\Pr(Y) \in [0,1]\)</span> (regression), then guess 1 if <span class="math inline">\(\Pr(Y) &gt; 0.5\)</span> (classification)</li>
</ul></li>
<li>By end of 5300 you should have something on your toolbelt for handling most cases like <em>“I want to do [regression / classification], but my data is [not cardinal+continuous]”</em></li>
</ul>
</section></section>
<section>
<section id="deriving-the-least-squares-estimate" class="title-slide slide level1 center" data-stack-name="Deriving OLS">
<h1>Deriving the Least Squares Estimate</h1>

</section>
<section id="a-sketch-hw-is-the-full-thing" class="slide level2 smaller crunch-title crunch-ul">
<h2>A Sketch (HW is the Full Thing)</h2>
<ul>
<li>OLS for regression <strong>without</strong> intercept: Which <span class="boxed"><strong>line through origin</strong></span> best predicts <span class="math inline">\(Y\)</span>?</li>
<li>(Good practice + reminder of how <strong>restricted</strong> linear models are!)</li>
</ul>
<p><span class="math display">\[
Y = \beta_1 X + \varepsilon
\]</span></p>

<img data-src="index_files/figure-revealjs/random-lines-origin-1.png" width="960" class="r-stretch"></section>
<section id="evaluating-with-residuals" class="slide level2 smaller">
<h2>Evaluating with Residuals</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/possible-choice-1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/choice-1-resid-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/possible-choice-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/choice-2-resid-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="now-the-math" class="slide level2 smaller">
<h2>Now the Math</h2>
<p><span class="math display">\[
\begin{align*}
\beta_1^* = \overbrace{\argmin}^{\begin{array}{c} \text{\small{Find thing}} \\[-5mm] \text{\small{that minimizes}}\end{array}}_{\beta_1}\left[ \sum_{i=1}^{n}(y_i - \widehat{y}_i)^2 \right] = \argmin_{\beta_1}\left[ \sum_{i=1}^{n}(y_i - \beta_1x_i)^2 \right]
\end{align*}
\]</span></p>
<p>We can compute this derivative to obtain:</p>
<p><span class="math display">\[
\frac{\partial}{\partial\beta_1}\left[ \sum_{i=1}^{n}(\beta_1x_i - y_i)^2 \right] = \sum_{i=1}^{n}\frac{\partial}{\partial\beta_1}(\beta_1x_i - y_i)^2 = \sum_{i=1}^{n}2(\beta_1x_i - y_i)x_i
\]</span></p>
<p>And our first-order condition means that:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}2(\beta_1^*x_i - y_i)x_i = 0 \iff \beta_1^*\sum_{i=1}^{n}x_i^2 = \sum_{i=1}^{n}x_iy_i \iff \boxed{\beta_1^* = \frac{\sum_{i=1}^{n}x_iy_i}{\sum_{i=1}^{n}x_i^2}}
\]</span></p>
</section></section>
<section>
<section id="doing-things-with-regression" class="title-slide slide level1 center" data-stack-name="Interpreting Results">
<h1>Doing Things With Regression</h1>

</section>
<section id="regression-r-vs.-statsmodels" class="slide level2 smaller output-75">
<h2>Regression: <code>R</code> vs.&nbsp;<code>statsmodels</code></h2>
<div class="columns">
<div class="column" style="width:45%;">
<center>
<strong>In (Base) R: <code>lm()</code></strong>
</center>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>lin_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> TV, <span class="at">data=</span>ad_df)</span>
<span id="cb7-2"><a></a><span class="fu">summary</span>(lin_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ TV, data = ad_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.3860 -1.9545 -0.1913  2.0671  7.2124 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 7.032594   0.457843   15.36   &lt;2e-16 ***
TV          0.047537   0.002691   17.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.259 on 198 degrees of freedom
Multiple R-squared:  0.6119,    Adjusted R-squared:  0.6099 
F-statistic: 312.1 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>General syntax:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">lm</span>(</span>
<span id="cb9-2"><a></a>  dependent <span class="sc">~</span> independent <span class="sc">+</span> controls,</span>
<span id="cb9-3"><a></a>  <span class="at">data =</span> my_df</span>
<span id="cb9-4"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column" style="width:55%;">
<center>
<strong>In Python: <code>smf.ols()</code></strong>
</center>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb10-2"><a></a>results <span class="op">=</span> smf.ols(<span class="st">"sales ~ TV"</span>, data<span class="op">=</span>ad_df).fit()</span>
<span id="cb10-3"><a></a><span class="bu">print</span>(results.summary(slim<span class="op">=</span><span class="va">True</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
No. Observations:                 200   F-statistic:                     312.1
Covariance Type:            nonrobust   Prob (F-statistic):           1.47e-42
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>General syntax:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a></a>smf.ols(</span>
<span id="cb12-2"><a></a>  <span class="st">"dependent ~ independent + controls"</span>,</span>
<span id="cb12-3"><a></a>  data <span class="op">=</span> my_df</span>
<span id="cb12-4"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></div>
</section>
<section id="interpreting-output" class="slide level2 smaller">
<h2>Interpreting Output</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/mil-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = military ~ industrial, data = gdp_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3354 -1.0997 -0.3870  0.6081  6.7508 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  0.61969    0.59526   1.041   0.3010  
industrial   0.05253    0.02019   2.602   0.0111 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.671 on 79 degrees of freedom
  (8 observations deleted due to missingness)
Multiple R-squared:  0.07895,   Adjusted R-squared:  0.06729 
F-statistic: 6.771 on 1 and 79 DF,  p-value: 0.01106</code></pre>
</div>
</div>
</div></div>
</section>
<section id="zooming-in-coefficients" class="slide level2 table-75 crunch-title">
<h2>Zooming In: Coefficients</h2>
<div class="coef-table">
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;|t|)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="cb1"><strong>(Intercept)</strong></span></td>
<td style="text-align: center;"><span class="cb1">0.61969</span></td>
<td><span class="cb1">0.59526</span></td>
<td><span class="cb1 bold">1.041</span></td>
<td><span class="cb1 bold">0.3010</span></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="cb2"><strong>industrial</strong></span></td>
<td style="text-align: center;"><span class="cb2">0.05253</span></td>
<td><span class="cb2">0.02019</span></td>
<td><span class="cb2 bold">2.602</span></td>
<td><span class="cb2 bold">0.0111</span></td>
<td><span class="cb2 bold">*</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><span class="coef-label"><span class="math inline">\(\widehat{\beta}\)</span></span></td>
<td><span class="coef-label">Uncertainty</span></td>
<td><span class="coef-label">Test stat <span class="math inline">\(t\)</span></span></td>
<td><span class="coef-label">How extreme is <span class="math inline">\(t\)</span>?</span></td>
<td><span class="coef-label">Signif. Level</span></td>
</tr>
</tbody>
</table>
</div>
<p><span class="math display">\[
\widehat{y} \approx \class{cb1}{\overset{\beta_0}{\underset{\small \pm 0.595}{0.620}}} +  \class{cb2}{\overset{\beta_1}{\underset{\small \pm 0.020}{0.053}}} \cdot x
\]</span></p>
</section>
<section id="zooming-in-significance" class="slide level2 crunch-title table-75 crunch-details crunch-quarto-figure">
<h2>Zooming In: Significance</h2>
<div class="coef-table">
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;|t|)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="cb1"><strong>(Intercept)</strong></span></td>
<td style="text-align: center;"><span class="cb1">0.61969</span></td>
<td><span class="cb1">0.59526</span></td>
<td><span class="cb1 bold">1.041</span></td>
<td><span class="cb1 bold">0.3010</span></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="cb2"><strong>industrial</strong></span></td>
<td style="text-align: center;"><span class="cb2">0.05253</span></td>
<td><span class="cb2">0.02019</span></td>
<td><span class="cb2 bold">2.602</span></td>
<td><span class="cb2 bold">0.0111</span></td>
<td><span class="cb2 bold">*</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: center;"><span class="coef-label"><span class="math inline">\(\widehat{\beta}\)</span></span></td>
<td><span class="coef-label">Uncertainty</span></td>
<td><span class="coef-label">Test stat <span class="math inline">\(t\)</span></span></td>
<td><span class="coef-label">How extreme is <span class="math inline">\(t\)</span>?</span></td>
<td><span class="coef-label">Signif. Level</span></td>
</tr>
</tbody>
</table>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/t-stat-intercept-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="index_files/figure-revealjs/t-stat-coef-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-residual-plot" class="slide level2 crunch-title crunch-images" data-name="Diagnostics">
<h2>The Residual Plot</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Recall <strong>homoskedasticity</strong> assumption: Given our model</p>
<p><span class="math display">\[
  y_i = \beta_0 + \beta_1x_i + \varepsilon_i
  \]</span></p>
<p>the errors <span class="math inline">\(\varepsilon_i\)</span> <strong>should not vary systematically with <span class="math inline">\(i\)</span></strong></p>
<p>Formally: <span class="math inline">\(\forall i \left[ \Var{\varepsilon_i} = \sigma^2 \right]\)</span></p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/residual-plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/heteroskedastic-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="q-q-plot" class="slide level2">
<h2>Q-Q Plot</h2>
<ul>
<li>If <span class="math inline">\((\widehat{y} - y) \sim \mathcal{N}(0, \sigma^2)\)</span>, points would lie on 45° line:</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/qq-plot-heteroskedastic-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/qq-plot-gdp-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-linear-regression" class="slide level2">
<h2>Multiple Linear Regression</h2>
<ul>
<li>Notation: <span class="math inline">\(x_{i,j}\)</span> = value of independent variable <span class="math inline">\(j\)</span> for person/observation <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(M\)</span> = total number of independent variables</li>
</ul>
<p><span class="math display">\[
\widehat{y}_i = \beta_0 + \beta_1x_{i,1} + \beta_2x_{i,2} + \cdots + \beta_M x_{i,M}
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_j\)</span> interpretation: a one-unit increase in <span class="math inline">\(x_{i,j}\)</span> is associated with a <span class="math inline">\(\beta_j\)</span> unit increase in <span class="math inline">\(y_i\)</span>, <strong>holding all other independent variables constant</strong></li>
</ul>
</section>
<section id="visualizing-multiple-linear-regression" class="slide level2 crunch-title title-09">
<h2>Visualizing Multiple Linear Regression</h2>

<img data-src="images/3_5.svg" class="r-stretch quarto-figure-center"><p class="caption">(ISLR Fig 3.5): <em>A pronounced non-linear relationship. Positive residuals (visible above the surface) tend to lie along the 45° line, where budgets are split evenly. Negative residuals (most not visible) tend to be away from this line, where budgets are more lopsided.</em></p></section>
<section id="interpreting-mlr" class="slide level2 text-75 crunch-title crunch-p">
<h2>Interpreting MLR</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ TV + radio + newspaper, data = ad_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.8277 -0.8908  0.2418  1.1893  2.8292 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.938889   0.311908   9.422   &lt;2e-16 ***
TV           0.045765   0.001395  32.809   &lt;2e-16 ***
radio        0.188530   0.008611  21.893   &lt;2e-16 ***
newspaper   -0.001037   0.005871  -0.177     0.86    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.686 on 196 degrees of freedom
Multiple R-squared:  0.8972,    Adjusted R-squared:  0.8956 
F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Holding <code>radio</code> and <code>newspaper</code> spending constant</strong>…</p>
<ul>
<li>An <strong>increase of $1K</strong> in spending on <code>TV</code> ads is associated with…</li>
<li>An <strong>increase in sales of 46 units</strong></li>
</ul>
<p><strong>Holding <code>TV</code> and <code>newspaper</code> spending constant</strong>…</p>
<ul>
<li>An <strong>increase of $1K</strong> in spending on <code>radio</code> ads is associated with…</li>
<li>An <strong>increase in sales of 189 units</strong></li>
</ul>
</div></div>
</section>
<section id="but-wait" class="slide level2 smaller crunch-title title-11 crunch-p crunch-math math-90">
<h2>But Wait…</h2>
<div class="columns">
<div class="column" style="width:50%;">
<center>
<p><span class="math display">\[
\texttt{sales} = \overset{*}{\beta_0} + \overset{*}{\beta_1}\texttt{newspaper}
\]</span></p>
</center>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) 12.351407   0.621420 19.8761 &lt; 2.2e-16 ***
newspaper    0.054693   0.016576  3.2996  0.001148 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<center>
<p><span class="math display">\[
\texttt{sales} = \overset{*}{\beta_0} + \overset{*}{\beta_1}\texttt{TV} + \overset{*}{\beta_2}\texttt{radio} + \overset{(~~)}{\beta_3}\texttt{paper}
\]</span></p>
</center>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.9388894  0.3119082  9.4223   &lt;2e-16 ***
TV           0.0457646  0.0013949 32.8086   &lt;2e-16 ***
radio        0.1885300  0.0086112 21.8935   &lt;2e-16 ***
newspaper   -0.0010375  0.0058710 -0.1767   0.8599    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div></div>
<div id="mlr-difference" style="font-size: 110%">
<ul>
<li><code>newspaper</code> <span class="math inline">\(\overset{*}{\rightarrow}\)</span> <code>sales</code> in SLR, but <code>newspaper</code> <span class="math inline">\(\overset{*}{\not\rightarrow}\)</span> <code>sales</code> in MLR?</li>
<li><strong>Correlations</strong> <span class="math inline">\(\Rightarrow\)</span> MLR results can be <strong>drastically different</strong> from SLR results</li>
<li>This is a good thing! It’s how we’re able to <strong>control for</strong> confounding vars!</li>
</ul>
</div>
</section>
<section id="correlations-among-features" class="slide level2 smaller">
<h2>Correlations Among Features</h2>
<div class="cell center-output">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">cor</span>(ad_df <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>id))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  TV      radio  newspaper     sales
TV        1.00000000 0.05480866 0.05664787 0.7822244
radio     0.05480866 1.00000000 0.35410375 0.5762226
newspaper 0.05664787 0.35410375 1.00000000 0.2282990
sales     0.78222442 0.57622257 0.22829903 1.0000000</code></pre>
</div>
</div>
<ul>
<li>Observe how <span class="math inline">\(\text{cor}(\texttt{radio}, \texttt{newspaper}) \approx 0.35\)</span> (highest feat-feat correlation)</li>
<li>In markets where we spend more on <code>radio</code> our sales will tend to be higher…</li>
<li>Corr matrix <span class="math inline">\(\implies\)</span> we spend more on <code>newspaper</code> in those same markets…</li>
<li>In SLR which only examines <code>sales</code> vs.&nbsp;<code>newspaper</code>, we (<strong>correctly!</strong>) observe that higher values of <code>newspaper</code> are associated with higher values of <code>sales</code>…</li>
<li>In essence, <code>newspaper</code> advertising is a <strong>surrogate</strong> for <code>radio</code> advertising <span class="math inline">\(\implies\)</span> in our SLR, <code>newspaper</code> “gets credit” for the association between <code>radio</code> and <code>sales</code></li>
</ul>
</section>
<section id="regression-superpower-incorporating-categorical-vars" class="slide level2 smaller title-09 math-90">
<h2>Regression Superpower: Incorporating Categorical Vars</h2>
<p><em>(Preview for next week)</em></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[
Y = \beta_0 + \beta_1 \times \texttt{income}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/credit-plot-slr-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><span class="math display">\[
\begin{align*}
Y = &amp;\beta_0 + \beta_1 \times \texttt{income} + \beta_2 \times \texttt{Student} \\
&amp;+ \beta_3 \times (\texttt{Student} \times \texttt{Income})
\end{align*}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/credit-plot-students-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<ul>
<li>How does the <span class="math inline">\(\texttt{Student} \times \texttt{Income}\)</span> term help?</li>
<li>Understanding this setup will open up a <strong>vast</strong> array of possibilities for regression 😎</li>
</ul>
</section></section>
<section>
<section id="quiz-review" class="title-slide slide level1 center" data-stack-name="Quiz">
<h1>Quiz Review</h1>

</section>
<section id="objective-functions" class="slide level2 crunch-title text-82 crunch-ul crunch-callout crunch-math">
<h2>Objective Functions</h2>
<p>“Fitting” a statistical model to data means <strong>minimizing</strong> some <strong>loss function</strong> that measures “how bad” our predictions are:</p>
<div title="Optimization Problems: General Form">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Optimization Problems: General Form</strong></p>
</div>
<div class="callout-content">
<p>Find <span class="math inline">\(x^*\)</span>, the solution to</p>
<p><span class="math display">\[
\begin{align}
    \min_{x} ~ &amp; f(x) &amp;\text{(Objective function)} \\
    \text{s.t. } ~ &amp; g(x) = 0 &amp;\text{(Constraints)}
\end{align}
\]</span></p>
</div>
</div>
</div>
</div>
<ul>
<li>Earlier we were able to write <span class="math inline">\(x^* = \argmax_x{f(x)}\)</span>, since there were no constraints. Is there a way to write a formula like this <em>with</em> constraints?</li>
<li>Answer: Yes! Thx Giuseppe-Luigi Lagrangia = Joseph-Louis <strong>Lagrange</strong>:</li>
</ul>
<p><span class="math display">\[
x^* = \argmax_{x,~\lambda}f(x) - \lambda[g(x)]
\]</span></p>

<aside><div>
<p><em>(Why worry about constraints when OLS is unconstrained? …Soon we’ll need to <strong>penalize complexity!</strong>)</em></p>
</div></aside></section>
<section id="example-problem" class="slide level2 text-80 crunch-title crunch-math-15">
<h2>Example Problem</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div title="Example 1: Unconstrained Optimization">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example 1: Unconstrained Optimization</strong></p>
</div>
<div class="callout-content">
<p>Find <span class="math inline">\(x^*\)</span>, the solution to</p>
<p><span class="math display">\[
\begin{align}
    \min_{x} ~ &amp; f(x) = 3x^2 - x \\
    \text{s.t. } ~ &amp; \varnothing
\end{align}
\]</span></p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div title="Our Plan">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Our Plan</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Compute the derivative <span class="math inline">\(f'(x) = \frac{\partial}{\partial x}f(x)\)</span>,</li>
<li>Set it equal to zero: <span class="math inline">\(f'(x) = 0\)</span>, and</li>
<li>Solve this equality for <span class="math inline">\(x\)</span>, i.e., find values <span class="math inline">\(x^*\)</span> satisfying <span class="math inline">\(f'(x^*) = 0\)</span></li>
</ul>
</div>
</div>
</div>
</div>
</div></div>
<p>Computing the derivative:</p>
<p><span class="math display">\[
f'(x) = \frac{\partial}{\partial x}f(x) = \frac{\partial}{\partial x}\left[3x^2 - x\right] = 6x - 1,
\]</span></p>
<p>Solving for <span class="math inline">\(x^*\)</span>, the value(s) satisfying <span class="math inline">\(\frac{\partial}{\partial x}f'(x^*) = 0\)</span> for just-derived <span class="math inline">\(f'(x)\)</span>:</p>
<p><span class="math display">\[
f'(x^*) = 0 \iff 6x^* - 1 = 0 \iff x^* = \frac{1}{6}.
\]</span></p>
</section>
<section id="derivative-cheatsheet" class="slide level2 smaller crunch-title title-12 text-65">
<h2>Derivative Cheatsheet</h2>
<colspec>
</colspec><table>
<colgroup><col style="width: 24%;">

<col style="width: 24%;">

<col style="width: 52%;">

</colgroup>
<thead>
<tr>
<th class="tdvc">
Type of Thing
</th>
<th class="tdvc">
Thing
</th>
<th>
Change in Thing when <span class="math inline">\(x\)</span> Changes by Tiny Amount
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Polynomial
</td>
<td>
<span class="math inline">\(f(x) = x^n\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = \frac{\partial}{\partial x}f(x) = nx^{n-1}\)</span>
</td>
</tr>
<tr>
<td class="tdvc">
Fraction
</td>
<td class="tdvc">
<span class="math inline">\(f(x) = \frac{1}{x}\)</span>
</td>
<td>
Use Polynomial rule (since <span class="math inline">\(\frac{1}{x} = x^{-1}\)</span>) to get <span class="math inline">\(f'(x) = -\frac{1}{x^2}\)</span>
</td>
</tr>
<tr>
<td>
Logarithm
</td>
<td>
<span class="math inline">\(f(x) = \ln(x)\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = \frac{\partial}{\partial x} = \frac{1}{x}\)</span>
</td>
</tr>
<tr>
<td>
Exponential
</td>
<td>
<span class="math inline">\(f(x) = e^x\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = \frac{\partial}{\partial x}e^x = e^x\)</span> (🧐❗️)
</td>
</tr>
<tr>
<td>
Multiplication
</td>
<td>
<span class="math inline">\(f(x) = g(x)h(x)\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = g'(x)h(x) + g(x)h'(x)\)</span>
</td>
</tr>
<tr>
<td class="tdvc">
Division
</td>
<td class="tdvc">
<span class="math inline">\(f(x) = \frac{g(x)}{h(x)}\)</span>
</td>
<td>
Too hard to memorize… turn it into Multiplication, as <span class="math inline">\(f(x) = g(x)(h(x))^{-1}\)</span>
</td>
</tr>
<tr>
<td>
Composition (Chain Rule)
</td>
<td class="tdvc">
<span class="math inline">\(f(x) = g(h(x))\)</span>
</td>
<td class="tdvc">
<span class="math inline">\(f'(x) = g'(h(x))h'(x)\)</span>
</td>
</tr>
<tr>
<td>
Fancy Logarithm
</td>
<td>
<span class="math inline">\(f(x) = \ln(g(x))\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = \frac{g'(x)}{g(x)}\)</span> by Chain Rule
</td>
</tr>
<tr>
<td>
Fancy Exponential
</td>
<td>
<span class="math inline">\(f(x) = e^{g(x)}\)</span>
</td>
<td>
<span class="math inline">\(f'(x) = g'(x)e^{g(x)}\)</span> by Chain Rule
</td>
</tr>
</tbody>
</table>
</section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-gelman_data_2007" class="csl-entry" role="listitem">
Gelman, Andrew, and Jennifer Hill. 2007. <em>Data <span>Analysis Using Regression</span> and <span>Multilevel</span>/<span>Hierarchical Models</span></em>. Cambridge University Press. <a href="https://www.dropbox.com/scl/fi/asbumi3g0gqa4xl9va7wp/Andrew-Gelman-Jennifer-Hill-Data-Analysis-Using-Regression-and-Multilevel_Hierarchical-Models.pdf?rlkey=zf8icjhm7rswvxrpm7d10m65o&amp;dl=1">https://www.dropbox.com/scl/fi/asbumi3g0gqa4xl9va7wp/Andrew-Gelman-Jennifer-Hill-Data-Analysis-Using-Regression-and-Multilevel_Hierarchical-Models.pdf?rlkey=zf8icjhm7rswvxrpm7d10m65o&amp;dl=1</a>.
</div>
<div id="ref-james_introduction_2023" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, Robert Tibshirani, and Jonathan Taylor. 2023. <em>An <span>Introduction</span> to <span>Statistical Learning</span>: With <span>Applications</span> in <span>Python</span></em>. Springer Nature. <a href="https://books.google.com?id=ygzJEAAAQBAJ">https://books.google.com?id=ygzJEAAAQBAJ</a>.
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>DSAN 5300 Week 2: Logistic Regression</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/simplemenu/simplemenu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'simplemenu': {"menubarclass":"menubar","menuclass":"menu","activeclass":"active","activeelement":"li","flat":true,"barhtml":{"header":"<div class='menubar'><span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span><ul class='menu'></ul></div>","footer":""},"scale":0.5},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, Simplemenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>